# Generated by Django 5.2.17 on 2026-10-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='store_order_user_id_f28375_idx',
            old_name='store_order_user_id_0d9d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='store_order_status_428b25_idx',
            old_name='store_order_status_9b9c8f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_categor_901851_idx',
            old_name='store_produc_categor_2dfe30_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_price_2d55a6_idx',
            old_name='store_produc_price_0f6f0f_idx',
        ),
    ]
